package com.tomasthrawat.blackbrowser

import java.net.URI
import java.net.URLDecoder
import java.net.URLEncoder
import java.nio.charset.StandardCharsets

object BrowserNavigation {
    private const val SEARCH_URL = "https://www.google.com/search"

    fun googleSearchUrl(query: String): String =
        SEARCH_URL + "?q=" + encodeQuery(query)

    /**
     * Returns true when two Google web-search URLs differ only by transient
     * navigation/telemetry parameters generated by Google itself.
     *
     * Only stable search parameters participate in the comparison, so search
     * mode (for example images/news via tbm) is preserved.
     */
    fun areEquivalentGoogleSearchUrls(first: String?, second: String?): Boolean {
        val a = normalizeGoogleSearchForComparison(first) ?: return false
        val b = normalizeGoogleSearchForComparison(second) ?: return false
        return a == b
    }

    private fun normalizeGoogleSearchForComparison(url: String?): List<Pair<String, String>>? {
        if (url.isNullOrBlank()) return null
        val uri = runCatching { URI(url) }.getOrNull() ?: return null
        val scheme = uri.scheme?.lowercase() ?: return null
        if (scheme != "http" && scheme != "https") return null
        val host = uri.host?.lowercase()?.removeSuffix(".") ?: return null
        if (host != "www.google.com" && host != "google.com") return null
        val path = (uri.path ?: "/").trimEnd('/')
        if (path != "/search") return null
        val query = uri.rawQuery ?: return null
        val stableKeys = setOf(
            "q", "tbm", "udm", "safe", "hl", "gl", "lr",
            "num", "start", "nfpr", "filter"
        )
        return query.split('&')
            .asSequence()
            .filter { it.isNotEmpty() }
            .map { part ->
                val separator = part.indexOf('=')
                val rawName = if (separator >= 0) part.substring(0, separator) else part
                val rawValue = if (separator >= 0) part.substring(separator + 1) else ""
                URLDecoder.decode(rawName, StandardCharsets.UTF_8.name()).lowercase() to
                    URLDecoder.decode(rawValue, StandardCharsets.UTF_8.name())
            }
            .filter { it.first in stableKeys }
            .sortedWith(compareBy<Pair<String, String>> { it.first }.thenBy { it.second })
            .toList()
            .takeIf { it.isNotEmpty() }
    }

    fun toUrl(rawInput: String): String {
        val input = rawInput.trim()
        if (input.isEmpty()) return ""

        val looksLikeUrl = input.contains(".") && !input.contains(" ")
        return if (looksLikeUrl) {
            when {
                input.startsWith("http://", ignoreCase = true) ||
                    input.startsWith("https://", ignoreCase = true) -> input
                else -> "https://" + input
            }
        } else {
            googleSearchUrl(input)
        }
    }

    private fun encodeQuery(input: String): String =
        URLEncoder.encode(input, StandardCharsets.UTF_8.name()).replace("+", "%20")
}
